name: C/C++ CI

on: push

jobs:
  build-and-test:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: install cppunit
      run: sudo apt install -y libcppunit-dev
      - name: configure
      run: ./configure
      - name: make
      run: make
      - name: make hello
      run: make hello