name: publish

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for tags starting with v*
  push:
    tags: ["v*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  publish-pypi:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest

      steps:
        - name: Check out repo
          uses: actions/checkout@v2

        - name: Build package
          run: |
            python3 -m pip install --upgrade build
            python3 -m build

        - name: Publish package
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            user: __token__
            password: ${{ secrets.PYPI_API_TOKEN }}
          if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
